proxy:
  host: 127.0.0.1
  port: 10809
    
download:
  single: 
    path: "C:\\ELOI\\pixiv\\single"
  keyword:
    path: "C:\\ELOI\\pixiv\\keyname"
  rank:
    path: "C:\\ELOI\\pixiv\\rank"
  tag:
    path: "C:\\ELOI\\pixiv\\tag"
  user:
    path: "C:\\ELOI\\pixiv\\user"

upload:
  use: true 
  endPoint: xxxxxxxxxxxxx:9000
  accessKeyID: xxxxxxxxxx
  secretAccessKey: xxxxxxxxxx
  useSSL: false
  bucketName: pixiv
  
