proxy:
  host: 127.0.0.1
  port: 10809
    
download:
  single: 
    path:
  keyword:
    path:
  rank:
    path:
  tag:
    path:

upload:
  endPoint: 81.69.203.181:9000
  accessKeyID: "yfaimisaka"
  secretAccessKey: "yfaimisaka"
  useSSL: false
  bucketName: pixiv
  
